[package]
name = "iconv-sys"
version = "0.2.0"
authors = ["Curtis Alexander <calex@calex.org>"]
edition = "2021"
description = "Bindings for iconv"
license = "MIT"
repository = "https://github.com/curtisalexander/readstat-rs/iconv-sys"
links = "iconv"
build = "build.rs"

[build-dependencies]
bindgen = "0.72"
cc = "1.2"
