[workspace]
members = [
    "crates/iconv-sys",
    "crates/readstat",
    "crates/readstat-cli",
    "crates/readstat-sys",

    # internal
    "crates/readstat-tests",
]
exclude = [
    "crates/readstat-wasm",
    "examples/api-demo/rust-server",
    "examples/api-demo/python-server/readstat_py",
]
resolver = "2"